name: hello-world
on: 
  push:
    branches:
      - 'test-gh-action-branch'
  pull_request:
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"

